# Generated by Django 5.0.2 on 2024-02-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ( 'email' , models.CharField(max_length = 200)),
                ('date_created' , models.DateTimeField(auto_now_add = True)),
                ('password', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
