# Generated by Django 4.2.10 on 2024-05-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product Name')),
                ('content', models.TextField(default='None', verbose_name='Content')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('seller', models.CharField(default='ShopSmall', max_length=120, verbose_name='Seller Name')),
                ('price', models.CharField(default='$0', max_length=120, verbose_name='Price')),
                ('businessID', models.IntegerField(verbose_name='Seller')),
                ('productID', models.IntegerField(verbose_name='Product ID')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
