# Generated by Django 5.0.2 on 2024-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='businessName',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
