# Generated by Django 5.0.2 on 2024-04-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='userName',
        ),
        migrations.AddField(
            model_name='testtable',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testtable',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='testtable',
            name='firstName',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='testtable',
            name='lastName',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=64, unique=True),
        ),
    ]
