# Generated by Django 4.2.10 on 2024-05-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testTable',
        ),
        migrations.AddField(
            model_name='product',
            name='businessID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='ShopSmall Company', max_length=100),
        ),
    ]
