# Generated by Django 5.0.2 on 2024-05-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cartitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/images/Lightning_McQueen.png', upload_to='product_images/'),
        ),
    ]
