# Generated by Django 4.2.10 on 2024-04-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='products',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default='None', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.bussiness'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
    ]
