# Generated by Django 5.0.2 on 2024-05-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/images/Lightning_McQueen.png', upload_to='static/images/'),
        ),
    ]
