# Generated by Django 5.0.2 on 2024-05-04 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
