# Generated by Django 4.2.10 on 2024-04-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_bussiness_products_remove_customers_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='creationDate',
            new_name='date_posted',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='$0', max_length=120, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='sellerB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.bussiness'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(default='ShopSmall', max_length=120, verbose_name='Seller Name'),
        ),
    ]
