# Generated by Django 5.0.2 on 2024-05-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/Lightning_McQueen.png', null=True, upload_to='static/images/'),
        ),
    ]
